apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  selector:
    app: simple-time-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
        - name: simple-time-service
          image: himanshududhatra/simpletimeservice:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "10m"
              memory: "50Mi"
            requests:
              cpu: "5m"
              memory: "25Mi"
          ports:
            - containerPort: 3000
